---
collections:
  - name: ansible.controller
    version: 4.4.2
  - name: awx.awx
    version: 23.2.0
  - name: aoc.controller_demo_config
    source: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
    version: v4.1.1
    type: git
